export const LITERATURE_SEARCH_SUBMITTED = 'LITERATURE_SEARCH_SUBMITTED'
export const LITERATURE_RESULTS_FOUND = 'LITERATURE_RESULTS_FOUND'
export const LITERATURE_SEARCH_PAGINATED = 'LITERATURE_SEARCH_PAGINATED'
export const LITERATURE_SEARCH_RESULTS_PAGINATED = 'LITERATURE_SEARCH_RESULTS_PAGINATED'
