export const SEARCH_INITIALIZED = 'SEARCH_INITIALIZED';
export const SEARCH_SUBMITTED = 'SEARCH_SUBMITTED';
export const SEARCH_RESULTS_RECEIVED = 'SEARCH_RESULTS_RECEIVED';
export const SEARCH_PAGINATED = "SEARCH_PAGINATED";
export const SEARCH_RESULTS_PAGINATED =  "SEARCH_RESULTS_PAGINATED";
