export const BRAIN_REGION_SEARCH_INITIALIZED = 'BRAIN_REGION_SEARCH_INITIALIZED'
export const BRAIN_REGION_SEARCH_SUBMITTED = 'BRAIN_REGION_SEARCH_SUBMITTED'
export const BRAIN_REGION_SEARCH_RESULTS_RECEIVED = 'BRAIN_REGION_SEARCH_RESULTS_RECEIVED'
export const BRAIN_REGION_SEARCH_PAGINATED = 'BRAIN_REGION_SEARCH_PAGINATED'

