export const ENTITY_UPDATE = 'ENTITY_UPDATE'
export const ENTITY_FOUND = 'ENTITY_FOUND'
export const ENTITY_LOADED = 'ENTITY_LOADED'
export const ENTITY_DATASPACE_RESULTS_FOUND = 'ENTITY_DATASPACE_RESULTS_FOUND'
