export const ENTITY_SEARCH_INITIALIZED = 'ENTITY_SEARCH_INITIALIZED'
export const ENTITY_SEARCH_SUBMITTED = 'ENTITY_SEARCH_SUBMITTED'
export const ENTITY_SEARCH_RESULTS_RECEIVED = 'ENTITY_SEARCH_RESULTS_RECEIVED'
export const ENTITY_SEARCH_PAGINATED = 'ENTITY_SEARCH_PAGINATED'
export const ENTITY_SEARCH_RESULTS_PAGINATED = 'ENTITY_SEARCH_RESULTS_PAGINATED'

export const ENTITY_RESULTS_COLUMNS = {curie: 'Curie', labels: 'Labels'}
